version: '2.2'
services:
  bot:
    image: breedish/mightytigersbot
    container_name: mightytigersbot
    ports:
      - "4000:3000"
      - "8443:443"
    environment: 
      - "MONGO_URI=${MONGO_URI}"
      - "BOT_TOKEN=${BOT_TOKEN}"