version: '3'
services:
  bot:
    image: breedish/mightytigersbot
    container_name: mightytigersbot
    deploy:
      replicas: 1
    ports:
      - "4000:3000"
      - "8443:443"
    environment:
      - "MONGO_URI=${MONGO_URI}"
      - "BOT_TOKEN=${BOT_TOKEN}"
    restart: on-failure
