apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ses-voting
  labels:
    app: bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: ses-voting
          image: gcr.io/ses-voting/ses-voting:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          env:
            - name: MONGO_URI
              value: "mongodb://tigers:tigers123@tigers-shard-00-00-yyyc0.mongodb.net:27017,tigers-shard-00-01-yyyc0.mongodb.net:27017,tigers-shard-00-02-yyyc0.mongodb.net:27017/test?ssl=true&replicaSet=tigers-shard-0&authSource=admin"
            - name: BOT_TOKEN
              value: "549031160:AAGhKf5JNWguQZPqR4y8NrjFHJm4Axp8mLQ"
            - name: TEST
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ses-voting
  labels:
    app: bot
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: bot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ses-voting
  labels:
    app: bot
data:
  service-name: ses-voting
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ses-voting
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ses-voting
spec:
  backend:
    serviceName: ses-voting
    servicePort: 3000
        